# Generated by Django 5.2.5 on 2025-09-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('AR', 'статья'), ('CD', 'карта дня')], default='CD', max_length=2),
        ),
    ]
